name: building-image-triplet-model
channels:
  - conda-forge
dependencies:
  - black=25.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - click=8.1.8
  - colorama=0.4.6
  - flake8=7.2.0
  - freetype=2.13.3
  - h5py=3.13.0
  - hdf5=1.14.3
  - isort=6.0.1
  - joblib=1.4.2
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libcxx=20.1.4
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.4
  - mccabe=0.7.0
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - numpy=2.2.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - pathspec=0.12.1
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - pthread-stubs=0.4
  - pycodestyle=2.13.0
  - pyflakes=3.3.2
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=80.1.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
    - h5py~=3.12.0
    - numpy~=2.2.2
    - optuna~=4.1.0
    - pillow~=11.1.0
    - rich~=14.0.0
    - scikit-learn~=1.5.2
    - scipy~=1.15.1
    - timm~=1.0.15
    - torch~=2.6.0
    - torchvision~=0.21.0
    - tqdm~=4.67.1
    - wandb~=0.19.6
    - lightning~=2.5.0
    - pyyaml~=6.0.1
    - pytest~=7.4.0